# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create_date',
            new_name='created_time',
        ),
    ]
