# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190723_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_time',
        ),
    ]
